# Generated by Django 5.2.8 on 2026-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Offers/'),
        ),
    ]
