# Generated by Django 5.2.8 on 2025-12-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0002_remove_offerdetails_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='coder_app.offers'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.FileField(default=True, null=True, upload_to='offers/'),
        ),
    ]
