# Generated by Django 5.2.8 on 2025-12-28 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0003_alter_offerdetails_offer_alter_offers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='coder_app.offerdetails'),
        ),
    ]
